# Generated by Django 2.1.5 on 2019-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
