"""
Django settings for consult project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "ttgezcz)q@ny8a-&()-1)pu9o+*xfg_u$+1g&rs!=17rt(=0km"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "django.contrib.postgres",
    "django.contrib.humanize",
    "django.contrib.gis",
    "corsheaders",
    "storages",
    "raven.contrib.django.raven_compat",
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    "two_factor",
    "rest_framework",
    "rest_framework.authtoken",
    "cotidia.core",
    "cotidia.admin",
    "cotidia.account",
    "cotidia.mail",
    "cotidia.file",
    "cotidia.actionable",
    "cotidia.team",
    "consult",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "two_factor.middleware.threadlocals.ThreadLocals",
    "cotidia.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "consult.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates/")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cotidia.account.context_processor.account_settings",
                "cotidia.admin.context_processor.admin_settings",
            ]
        },
    }
]

WSGI_APPLICATION = "consult.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "consultdemo",
        "USER": "",
        "PASSWORD": "",
        "HOST": "127.0.0.1",
        "PORT": "",
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"

# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"require_debug_false": {"()": "django.utils.log.RequireDebugFalse"}},
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
        "null": {"class": "logging.NullHandler"},
    },
    "loggers": {
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
        "django.security.DisallowedHost": {"handlers": ["null"], "propagate": False},
    },
}

# Static files

# Where to collect static files
STATIC_ROOT = os.path.join(BASE_DIR, "../static")
# The url prefix
STATIC_URL = "/static/"
# Where to serve static files in DEBUG mode
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# Email

DEFAULT_FROM_EMAIL = "Cotidia Connect <info@cotidia.com>"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST = "smtp.mandrillapp.com"
EMAIL_HOST_USER = os.path.join("MANDRILL_USERNAME", "key-not-set")
EMAIL_HOST_PASSWORD = os.path.join("MANDRILL_API_KEY", "key-not-set")

COTIMAIL_REPLY_EMAIL = DEFAULT_FROM_EMAIL
COTIMAIL_SENDER = DEFAULT_FROM_EMAIL
COTIMAIL_APPS = ["cotidia.account.notices", "consult.notices"]
COTIMAIL_QUEUE_MAIL = False
COTIMAIL_LOG_MAIL = True

# Language

DEFAULT_LANGUAGE = "en-gb"

# Rest Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "EXCEPTION_HANDLER": "cotidia.core.utils.exceptions.drf_exception_handler",
    "COERCE_DECIMAL_TO_STRING": False,
}

# Cotidia Connect specifics

SITE_URL = "http://localhost:8000"
SITE_NAME = "Cotidia Connect"

AUTHOR_URL = "https://cotidia.com"
AUTHOR = "Cotidia"

ADMIN_MENU_DEFINITION = {
    "Menu": ["consult", "cotidia.team", "cotidia.account"],
    "Mail": ["cotidia.mail"],
    # "Actionable": ["cotidia.actionable"],
}
ADMIN_SHOW_DEFAULT_MENU = False
ADMIN_SHOW_BRANDING = True
ADMIN_SITE_LOGO = "/img/cotidia-connect-logo@2x.png"

# CORS_ORIGIN_WHITELIST = ("localhost:8080",)

AUTH_USER_MODEL = "account.User"
AUTHENTICATION_BACKENDS = ("cotidia.account.auth.EmailBackend",)

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = reverse_lazy("account-admin:login")
LOGOUT_URL = reverse_lazy("account-admin:logout")
PASSWORD_RESET_TIMEOUT_DAYS = 7

ACCOUNT_ADMIN_LOGIN_URL = LOGIN_URL
ACCOUNT_FORCE_ACTIVATION = False
ACCOUNT_ENABLE_TWO_FACTOR = True
ACCOUNT_FORCE_ADMIN_TWO_FACTOR = False
